import type { Metadata } from "next";
import { Jost, Inter, Geist_Mono } from "next/font/google";
import ReduxProvider from "@/store/ReduxProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jost.variable} ${inter.variable} ${geistMono.variable}`}
    >
      <body className="antialiased">
        <TooltipProvider>
          <ReduxProvider>{children}</ReduxProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
